[package]
name = "rust_sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.32.1", features = ["hooks", "uuid", "chrono", "serde_json"] }
uuid = { version = "1.12.0", features = ["v7"]}
chrono = { version = "0.4.39", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"]}
serde_json = "1.0.135"